# Missing-Value dan Normalisasi

# Normalisasi

Normalisasi adalah salah satu teknik persiapan data yang paling sering digunakan. Pada  machine learning dan  data mining, proses ini membantu kita mengubah nilai kolom numerik dalam dataset untuk menggunakan skala umum.
Tujuan utama dari normalisasi data yakni menghilangkan redundansi data (pengulangan) dan menstandarisasi informasi untuk alur kerja data yang lebih baik. Pembelajaran Mesin & Kecerdasan Buatan

Normalisasi data digunakan untuk menskalakan data suatu atribut sehingga berada dalam rentang yang lebih kecil, seperti -1 hingga 1 atau 0 hingga 1. Hal ini umumnya berguna untuk algoritma klasifikasi. 

Ada 3 Macam Normalisasi, yaitu:

## Min-Max Normalization

Min–Max Normalisasi adalah metode untuk mengubah nilai data numerik agar berada dalam rentang tertentu, biasanya 0 sampai 1 dengan menggunakan nilai terendah(min) dan nilai tertinggi(max). Tujuannya supaya skala antar fitur menjadi sama dan tidak ada nilai yang terlalu besar dibanding yang lain.

Rumus Min-Max Normalisasi:

$x' = \frac{x - x_{min}}{x_{max} - x_{min}}$

Contoh Min-Max Normalisasi:

| data |
|--------|
| 20 |
| 30 |
| 40 |

Min = 20, Max = 40

data ke-1
$x' = \frac{20 - 20}{40 - 20} = 0$

data ke-2
$x' = \frac{30 - 20}{40 - 20} = 0.5$

data ke-3
$x' = \frac{40 - 20}{40 - 20} = 1$

|data|normalisasi|
|----|-----------|
|20|0|
|30|0.5|
|40|1|

In [1]:
def min_max(data):
    normalisasi = []
    angka_min = min(data)
    angka_max = max(data)
    for i in range(len(data)):
        jumlah = (data[i] - angka_min) / (angka_max - angka_min)
        normalisasi.append(jumlah)
    return normalisasi

data = [20,30,40]
min_max(data)

[0.0, 0.5, 1.0]

## Z-score Normalization

Z-score normalisasi (atau standardisasi) adalah metode normalisasi data yang mengubah nilai sehingga memiliki rata-rata (mean) = 0 dan simpangan baku (standar deviasi) = 1.
Metode ini menunjukkan seberapa jauh suatu nilai menyimpang dari rata-rata data dalam satuan standar deviasi.
Contoh interpretasi:

* Z = 0 → nilai sama dengan rata-rata
* Z = 1 → nilai 1 standar deviasi di atas rata-rata
* Z = −1 → nilai 1 standar deviasi di bawah rata-rata

Rumus Z-score Normalisasi:

$z = \frac{x - \mu}{\sigma}$

Keterangan:
* x = nilai data
* μ = rata-rata (mean) data
* σ = standar deviasi
* z = nilai hasil normalisasi (z-score)

Cara Menghitung Z-core Normalisasi:

|data|
|---|
|20|
|40|
|50|
|70|

* Menghitung Rata-Rata

$\mu = \frac{20 + 40 + 50 + 70}{4} = 45$

* Menghitung Standar Deviasi

$\sigma = \sqrt{\frac{(20-45)^2 + (40-45)^2 + (50-45)^2 + (70-45)^2}{4}} = \sqrt{\frac{625 + 25 + 25 + 625}{4}} = \sqrt{\frac{1300}{4}} = \sqrt{325} = 18.03$

* Menghitung Z-score

   * data ke-1

   $z = \frac{20 - 45}{18.03} = -1.39$

   * data ke-2

   $z = \frac{40 - 45}{18.03} = -0.28$

   * data ke-3

   $z = \frac{50 - 45}{18.03} = 0.28$

   * data ke-4

   $z = \frac{70 - 45}{18.03} = 1.39$

* Hasil Z-score Normalisasi

    |data|Normalisasi|
    |---|---|
    |20|-1.39|
    |40|-0.28|
    |50|0.28|
    |70|1.39|

In [2]:
import math

def z_score(data):
    normalisasi = []
    deviasi = 0
    mean = sum(data) / len(data)
    for i in range(len(data)):
        deviasi += (data[i] - mean) ** 2
    
    std_dev = math.sqrt(deviasi / len(data))

    for i in range(len(data)):
        z = (data[i] - mean) / std_dev
        z = round(z, 2)
        normalisasi.append(z)
    
    return normalisasi

data = [20,40,50,70]
z_score(data)

[-1.39, -0.28, 0.28, 1.39]

## Decimal Scaling Normalization

Decimal Scaling Normalization adalah metode normalisasi data dengan cara menggeser posisi desimal pada nilai data sampai semua nilai berada dalam rentang tertentu (biasanya antara −1 sampai 1).

Rumus Decimal Scaling Normalisasi:

$x' = \frac{x}{10^j}$

Keterangan:
* x = nilai data asli
* x′= nilai setelah normalisasi
* 𝑗 = jumlah digit dari nilai terbesar (atau jumlah pergeseran desimal)

Cara Decimal Scaling Normalisasi:

|data|
|---|
|30|
|80|
|350|
|200|
|760|

* Tentukan angka terbesar dalam kolom data

Angka terbesar dalam data adalah 760, Karena 760 memiliki 3 digit angka maka j = 3, berarti rumus menjadi:

$x' = \frac{x}{10^3}$

* menghitung Decimal Scalling Normalization

    * data ke-1

    $x' = \frac{30}{10^3} = 0.03$

    * data ke-2

    $x' = \frac{80}{10^3} = 0.08$

    * data ke-3

    $x' = \frac{350}{10^3} = 0.35$

    * data ke-4

    $x' = \frac{200}{10^3} = 0.2$

    * data ke-5

    $x' = \frac{200}{10^3} = 0.76$

* Hasil Decimal Scaling Normalisasi

    |data|Normalisasi|
    |---|----|
    |30|0.03|
    |80|0.08|
    |350|0.35|
    |200|0.2|
    |760|0.76|

In [3]:
def decimal_scaling(data):
    normalisasi = []
    angka_max = max(data)
    j = len(str(int(angka_max)))
    for i in range(len(data)):
        normalisasi.append(data[i] / (10 ** j))
    return normalisasi

data = [30,80,350,200,760]
decimal_scaling(data)

[0.03, 0.08, 0.35, 0.2, 0.76]

# Missing Value

Missing value dengan WKNN (Weighted K-Nearest Neighbor) adalah metode untuk mengisi data yang kosong dengan memanfaatkan nilai dari tetangga terdekat (neighbor), tetapi setiap tetangga diberi bobot (weight) berdasarkan jaraknya.

Cara Mencari Data Missing Value:

## Dataset

<table border="1" cellpadding="8" cellspacing="0" style="width:100%">
    <thead>
        <tr>
            <th>id</th>
            <th>umur</th>
            <th>pendapatan</th>
            <th>skor</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>1</td>
            <td>25</td>
            <td>3000</td>
            <td>60</td>
        </tr>
        <tr>
            <td>2</td>
            <td>30</td>
            <td>4000</td>
            <td>?</td>
        </tr>
        <tr>
            <td>3</td>
            <td>22</td>
            <td>2500</td>
            <td>55</td>
        </tr>
        <tr>
            <td>4</td>
            <td>35</td>
            <td>5000</td>
            <td>70</td>
        </tr>
        <tr>
            <td>5</td>
            <td>28</td>
            <td>3500</td>
            <td>65</td>
        </tr>
    </tbody>
</table>

Dalam dataset tersebut Angka skor pada baris ke-2 hilang dan akan dicari dengan Menggunakan WKNN.

## WKNN

### Perhitungan Manual

#### Menghitung Jarak Menggunakan Euclidean Distance

Menggunakan Rumus:

$d = \sqrt{\sum (x_i - y_i)^2}$

Pada dataset tersebut, Data ke-2 memiliki Umur = 30 dan Pendapatan = 4000, maka:

Data ke-1:

$d = \sqrt{(30-25)^2 + (4000-3000)^2} = \sqrt{25 + 1000000} = \sqrt{1000025} = 1000.01$

Data ke-3:

$d = \sqrt{(30-22)^2 + (4000-2500)^2} = \sqrt{64 + 2250000} = \sqrt{2250064} = 1500.02$

Data ke-4:

$d = \sqrt{(30-35)^2 + (4000-5000)^2} = \sqrt{25 + 1000000} = \sqrt{1000025} = 1000.01$

Data ke-5:

$d = \sqrt{(30-28)^2 + (4000-3500)^2} = \sqrt{4 + 250000}  = \sqrt{250004} = 500$

<table border="1" cellpadding="8" cellspacing="0" style="width:100%">
    <thead>
        <tr>
            <th>id</th>
            <th>umur</th>
            <th>pendapatan</th>
            <th>skor</th>
            <th>jarak</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>1</td>
            <td>25</td>
            <td>3000</td>
            <td>60</td>
            <td>1000.01</td>
        </tr>
        <tr>
            <td>3</td>
            <td>22</td>
            <td>2500</td>
            <td>55</td>
            <td>1500.02</td>
        </tr>
        <tr>
            <td>4</td>
            <td>35</td>
            <td>5000</td>
            <td>70</td>
            <td>1000.01</td>
        </tr>
        <tr>
            <td>5</td>
            <td>28</td>
            <td>3500</td>
            <td>65</td>
            <td>500</td>
        </tr>
    </tbody>
</table>

#### Hitung Bobot

Menggunakan Rumus:

$w = \frac{1}{d}$

Lakukan hitung bobot pada setiap data:

data ke-1:

$ w = \frac{1}{1000.01} = 0.001 $

data ke-3:

$ w = \frac{1}{1500.02} = 0.0006 $

data ke-4:

$ w = \frac{1}{1000.01} = 0.001 $

data ke-5:

$ w = \frac{1}{500} = 0.002 $

<table border="1" cellpadding="8" cellspacing="0" style="width:100%">
    <thead>
        <tr>
            <th>id</th>
            <th>umur</th>
            <th>pendapatan</th>
            <th>skor</th>
            <th>jarak</th>
            <th>bobot</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>1</td>
            <td>25</td>
            <td>3000</td>
            <td>60</td>
            <td>1000.01</td>
            <td>0.001</td>
        </tr>
        <tr>
            <td>3</td>
            <td>22</td>
            <td>2500</td>
            <td>55</td>
            <td>1500.02</td>
            <td>0.0006</td>
        </tr>
        <tr>
            <td>4</td>
            <td>35</td>
            <td>5000</td>
            <td>70</td>
            <td>1000.01</td>
            <td>0.001</td>
        </tr>
        <tr>
            <td>5</td>
            <td>28</td>
            <td>3500</td>
            <td>65</td>
            <td>500</td>
            <td>0.002</td>
        </tr>
    </tbody>
</table>

#### Menghitung WKNN

Menggunakan Rumus:

$x' = \frac{\sum w_i \cdot x_i}{\sum w_i}$

Masukkan semua bobot dan skor yang telah dilakukan sebelumnya:

$x' = \frac{ (0.001 \cdot 60) + (0.0006 \cdot 55) + (0.001 \cdot 70) + (0.002 \cdot 65)}{0.001 + 0.0006 + 0.001 + 0.002} = \frac{0.06 + 0.033 + 0.07 + 0.13}{0.0046} = \frac{0.293}{0.0046} = 63.70 \approx 64$

Dari perhitungan diatas maka nilai skor pada baris ke-2 adalah 64

<table border="1" cellpadding="8" cellspacing="0" style="width:100%">
    <thead>
        <tr>
            <th>id</th>
            <th>umur</th>
            <th>pendapatan</th>
            <th>skor</th>
            <th>jarak</th>
            <th>bobot</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>1</td>
            <td>25</td>
            <td>3000</td>
            <td>60</td>
            <td>1000.01</td>
            <td>0.001</td>
        </tr>
        <tr>
            <td>2</td>
            <td>30</td>
            <td>4000</td>
            <td>64</td>
        </tr>
        <tr>
            <td>3</td>
            <td>22</td>
            <td>2500</td>
            <td>55</td>
            <td>1500.02</td>
            <td>0.0006</td>
        </tr>
        <tr>
            <td>4</td>
            <td>35</td>
            <td>5000</td>
            <td>70</td>
            <td>1000.01</td>
            <td>0.001</td>
        </tr>
        <tr>
            <td>5</td>
            <td>28</td>
            <td>3500</td>
            <td>65</td>
            <td>500</td>
            <td>0.002</td>
        </tr>
    </tbody>
</table>

### Menggunakan Code Python

#### Dataset

In [4]:
import pandas as pd
import numpy as np

data = {
    'umur': [25, 30, 22, 35, 28],
    'pendapatan': [3000, 4000, 2500, 5000, 3500],
    'skor': [60, np.nan, 55, 70, 65]
}

data_sementara = {
    'umur': [25,22, 35, 28],
    'pendapatan': [3000,2500, 5000, 3500],
    'skor': [60,55, 70, 65]
}

pd.DataFrame(data)

   umur  pendapatan  skor
0    25        3000  60.0
1    30        4000   NaN
2    22        2500  55.0
3    35        5000  70.0
4    28        3500  65.0

#### Menghitung Jarak

In [5]:
import math
import pandas as pd

skor = []
umur = 30
pendapatan = 4000
for i in data['skor']:
    if not np.isnan(i):
        skor.append(i)

hasil_jarak = []
for i in range(len(data['umur'])):
    if np.isnan(data['skor'][i]):
        continue
    
    u = data['umur'][i]
    p = data['pendapatan'][i]
    
    jarak = math.sqrt((u - umur)**2 + (p - pendapatan)**2)
    
    hasil_jarak.append((round(jarak, 2)))



data_sementara["jarak"] = hasil_jarak
pd.DataFrame(data_sementara, columns=['umur', 'pendapatan', 'skor', 'jarak'])

   umur  pendapatan  skor    jarak
0    25        3000    60  1000.01
1    22        2500    55  1500.02
2    35        5000    70  1000.01
3    28        3500    65   500.00

#### Menghitung Bobot

In [6]:
import pandas as pd

bobot = []
for i in data_sementara["jarak"]:
    bagi = 1 / i
    bobot.append(round(bagi, 5))

data_sementara["bobot"] = bobot

pd.DataFrame(data_sementara)

   umur  pendapatan  skor    jarak    bobot
0    25        3000    60  1000.01  0.00100
1    22        2500    55  1500.02  0.00067
2    35        5000    70  1000.01  0.00100
3    28        3500    65   500.00  0.00200

#### Menghitung WKNN

In [7]:
import pandas as pd
from zmq import has

total_bobot = sum(data_sementara["bobot"])
jumlah = 0

for i in range(len(data_sementara["bobot"])):
    jumlah += data_sementara["skor"][i] * data_sementara["bobot"][i]

hasil_akhir = jumlah / total_bobot
hasil_akhir = round(hasil_akhir)

print("Hasil Prediksi Skor:", hasil_akhir)
print("")
print("Data Hasil Prediksi:")
data["skor"][1] = hasil_akhir
pd.DataFrame(data)

Hasil Prediksi Skor: 64

Data Hasil Prediksi:

   umur  pendapatan  skor
0    25        3000    60
1    30        4000    64
2    22        2500    55
3    35        5000    70
4    28        3500    65